// <auto-generated />
using System;
using CapstoneProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CapstoneProject.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200428162149_AddedMoreAnimals")]
    partial class AddedMoreAnimals
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CapstoneProject.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Age")
                        .HasColumnType("text");

                    b.Property<string>("Breed")
                        .HasColumnType("text");

                    b.Property<string>("CatOrDog")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("GoodWith")
                        .HasColumnType("text");

                    b.Property<bool>("GoodWithSmallChildren")
                        .HasColumnType("boolean");

                    b.Property<string>("HousingType")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNeutered")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVaccinated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("NeedYard")
                        .HasColumnType("boolean");

                    b.Property<string>("RescueCenter")
                        .HasColumnType("text");

                    b.Property<string>("Zipcode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = "4 years old",
                            Breed = "Greyhound",
                            CatOrDog = "dog",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 724, DateTimeKind.Local).AddTicks(3190),
                            Description = "Jack is a retired race dog who wants to spend the rest of his days with a family who will love and care for him. He would do best in a home that has a fenced yard.",
                            Gender = "Male",
                            GoodWith = "cat and dog",
                            GoodWithSmallChildren = true,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1587665893/greyhound_yqahgy.jpg",
                            IsActive = true,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Jack",
                            NeedYard = true,
                            RescueCenter = "Greyhounds of Florida",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 2,
                            Age = "6 years old",
                            Breed = "Tabby",
                            CatOrDog = "cat",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(4420),
                            Description = "Honey is a sweet girl who is looking for someone with a comfy lap and has time to pet her for days.",
                            Gender = "Female",
                            GoodWith = "cat",
                            GoodWithSmallChildren = true,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1587665853/tabby_vuruuf.jpg",
                            IsActive = true,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Honey",
                            NeedYard = true,
                            RescueCenter = "PetPal Animal Shelter",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 3,
                            Age = "4 years old",
                            Breed = "Golden Retriever",
                            CatOrDog = "dog",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(4470),
                            Description = "Buddy is looking for a new family to take him home and play fetch all day and night. His favorite thing is play outside!",
                            Gender = "Male",
                            GoodWith = "dog",
                            GoodWithSmallChildren = true,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1587665858/buddy_p2ej5y.jpg",
                            IsActive = true,
                            IsNeutered = false,
                            IsVaccinated = true,
                            Name = "Buddy",
                            NeedYard = true,
                            RescueCenter = "ASPCA",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 4,
                            Age = "7 years old",
                            Breed = "Terrier",
                            CatOrDog = "dog",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(4500),
                            Description = "Sweetie justs wants to curl up on the couch next to you and watch movies all day. She will make the perfect snuggle baby for someone!",
                            Gender = "Female",
                            GoodWith = "none ",
                            GoodWithSmallChildren = true,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1587665839/sweetie_plo8jp.jpg",
                            IsActive = true,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Sweetie",
                            NeedYard = true,
                            RescueCenter = "ASPCA",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 5,
                            Age = "3 years old",
                            Breed = "Poodle",
                            CatOrDog = "dog",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(4520),
                            Description = "Rocco is a very rambunctious poodle with loads of spunky personality. Everyone on your block will know who Rocco is!",
                            Gender = "Male",
                            GoodWith = "cat",
                            GoodWithSmallChildren = true,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1587665873/rocco_lrufwb.jpg",
                            IsActive = true,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Rocco",
                            NeedYard = true,
                            RescueCenter = "ASPCA",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 6,
                            Age = "2 years old",
                            Breed = "Pitbull",
                            CatOrDog = "dog",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(4540),
                            Description = "Sophie is a fun loving girl who wants to play always. Throw a frisbee or take her running, either way, she will keep up!",
                            Gender = "Female",
                            GoodWith = "cat and dog",
                            GoodWithSmallChildren = true,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1587665871/sophie_ol55co.jpg",
                            IsActive = true,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Sophie",
                            NeedYard = false,
                            RescueCenter = "ASPCA",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 7,
                            Age = "3 years old",
                            Breed = "Siberian Husky",
                            CatOrDog = "dog",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(4570),
                            Description = "Rex would do really well in a home where he is the only animal. He needs a lot of attention as he is a working dog so someone who can commit to taking long walks with Rex would be perfect!",
                            Gender = "Male",
                            GoodWith = "none",
                            GoodWithSmallChildren = true,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1587665873/rex_tfv6ya.jpg",
                            IsActive = true,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Rex",
                            NeedYard = false,
                            RescueCenter = "ASPCA",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 8,
                            Age = "2 years old",
                            Breed = "Domestic Short Hair",
                            CatOrDog = "cat",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(4720),
                            Description = "Chloe wants all the pets in the whole world!",
                            Gender = "Female",
                            GoodWith = "cat",
                            GoodWithSmallChildren = false,
                            HousingType = "apartment",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1587665870/chloe_uyhyyu.jpg",
                            IsActive = false,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Chloe",
                            NeedYard = false,
                            RescueCenter = "ASPCA",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 9,
                            Age = "1 years old",
                            Breed = "Persian",
                            CatOrDog = "cat",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(4740),
                            Description = "Dexter is the laziest Persian cat you have ever met. All he wants to do is be held in your arms while you pet him endlessly until he falls asleep!",
                            Gender = "Male",
                            GoodWith = "cat",
                            GoodWithSmallChildren = false,
                            HousingType = "apartment",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1587665887/dexter_qa3x0v.jpg",
                            IsActive = false,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Dexter",
                            NeedYard = false,
                            RescueCenter = "ASPCA",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 10,
                            Age = "1 years old",
                            Breed = "Domestic Short Hair",
                            CatOrDog = "cat",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(4770),
                            Description = "Ella is looking for a new furever home!",
                            Gender = "Female",
                            GoodWith = "none",
                            GoodWithSmallChildren = false,
                            HousingType = "apartment",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1587665883/ella_kknwpn.jpg",
                            IsActive = false,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Ella",
                            NeedYard = false,
                            RescueCenter = "ASPCA",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 11,
                            Age = "4 years old",
                            Breed = "Russian Blue",
                            CatOrDog = "cat",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(4790),
                            Description = "If you have ever wanted a cat who never stops exploring, you have found him! Simon loves to be outside and roam the outdoors but he will never venture too far from home!",
                            Gender = "Male",
                            GoodWith = "cat and dog",
                            GoodWithSmallChildren = true,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1587665891/simon_kf7ksd.jpg",
                            IsActive = true,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Simon",
                            NeedYard = true,
                            RescueCenter = "ASPCA",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 12,
                            Age = "2 years old",
                            Breed = "Domestic Long Hair",
                            CatOrDog = "cat",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(4810),
                            Description = "Sheba will be the princess of the house with an attitude to match...but only because she wants attention!",
                            Gender = "Female",
                            GoodWith = "none",
                            GoodWithSmallChildren = true,
                            HousingType = "apartment",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1587665886/sheba_q2wn4u.jpg",
                            IsActive = false,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Sheba",
                            NeedYard = false,
                            RescueCenter = "ASPCA",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 13,
                            Age = "3 years old",
                            Breed = "Domestic Medium Hair",
                            CatOrDog = "cat",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(4830),
                            Description = "Nala wants nothing more than to find a spot perched high above your head so she can watch her family down below!",
                            Gender = "Female",
                            GoodWith = "none",
                            GoodWithSmallChildren = true,
                            HousingType = "apartment",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1587665885/nala_yyucg3.jpg",
                            IsActive = false,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Nala",
                            NeedYard = false,
                            RescueCenter = "ASPCA",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 14,
                            Age = " 6 months old",
                            Breed = "Brown Tabby",
                            CatOrDog = "cat",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(4850),
                            Description = "Just a little baby Harry is, someone love him!",
                            Gender = "Male",
                            GoodWith = "cat",
                            GoodWithSmallChildren = true,
                            HousingType = "apartment",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1587665885/harry_rtszsw.jpg",
                            IsActive = false,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Harry",
                            NeedYard = false,
                            RescueCenter = "ASPCA",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 15,
                            Age = " 1 years old",
                            Breed = "Pug",
                            CatOrDog = "dog",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(4870),
                            Description = "Maggie loves to be a couch potato and will snuggle up right next to you!",
                            Gender = "Female",
                            GoodWith = "cat and dog",
                            GoodWithSmallChildren = true,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1588008900/maggie_mvuo8d.jpg",
                            IsActive = true,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Maggie",
                            NeedYard = true,
                            RescueCenter = "PetPal Animal Shelter",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 16,
                            Age = "5 years old",
                            Breed = "French Bulldog",
                            CatOrDog = "dog",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(4890),
                            Description = "Dunkin is a very athletic dog that loves to play firsbee or pull you on your skateboard!",
                            Gender = "Male",
                            GoodWith = "none",
                            GoodWithSmallChildren = true,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1588009236/dunkin_glzbgz.jpg",
                            IsActive = true,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Dunkin",
                            NeedYard = true,
                            RescueCenter = "PetPal Animal Shelter",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 17,
                            Age = "3 years old",
                            Breed = "Pitbull",
                            CatOrDog = "dog",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(4910),
                            Description = "",
                            Gender = "Male",
                            GoodWith = "cat",
                            GoodWithSmallChildren = true,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1588088810/blake_wz3o4g.jpg",
                            IsActive = true,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Blake",
                            NeedYard = false,
                            RescueCenter = "ASPCA",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 18,
                            Age = "5 years old",
                            Breed = "Pitbull",
                            CatOrDog = "dog",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(4930),
                            Description = "",
                            Gender = "Female",
                            GoodWith = "dog",
                            GoodWithSmallChildren = true,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1588088810/stella_hsa5km.jpg",
                            IsActive = true,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Stella",
                            NeedYard = false,
                            RescueCenter = "PetPal Animal Shelter",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 19,
                            Age = "2 years old",
                            Breed = "Dalmatian",
                            CatOrDog = "dog",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(4950),
                            Description = "",
                            Gender = "Male",
                            GoodWith = "dog",
                            GoodWithSmallChildren = false,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1588088816/maverick_sxaj1x.jpg",
                            IsActive = true,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Maverick",
                            NeedYard = true,
                            RescueCenter = "PetPal Animal Shelter",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 20,
                            Age = "6 months old",
                            Breed = "Yorkie",
                            CatOrDog = "dog",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(4970),
                            Description = "",
                            Gender = "Male",
                            GoodWith = "cat",
                            GoodWithSmallChildren = false,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1588088814/oliver_o4ep1l.jpg",
                            IsActive = true,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Oliver",
                            NeedYard = true,
                            RescueCenter = "PetPal Animal Shelter",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 21,
                            Age = "6 months old",
                            Breed = "Labordor Retriever",
                            CatOrDog = "dog",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(4990),
                            Description = "",
                            Gender = "Male",
                            GoodWith = "cat and dog",
                            GoodWithSmallChildren = false,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1588088814/zack_d8t07o.jpg",
                            IsActive = true,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Zack",
                            NeedYard = true,
                            RescueCenter = "PetPal Animal Shelter",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 22,
                            Age = "1 years old",
                            Breed = "Corgi",
                            CatOrDog = "dog",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(5010),
                            Description = "",
                            Gender = "Female",
                            GoodWith = "none",
                            GoodWithSmallChildren = false,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1588088812/tesla_hb1hsb.jpg",
                            IsActive = true,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Tesla",
                            NeedYard = true,
                            RescueCenter = "Humane Society of Pinellas",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 23,
                            Age = "4 years old",
                            Breed = "Australian Shepard",
                            CatOrDog = "dog",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(5030),
                            Description = "",
                            Gender = "Female",
                            GoodWith = "dog",
                            GoodWithSmallChildren = false,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1588088809/macy_csaskg.jpg",
                            IsActive = false,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Macy",
                            NeedYard = true,
                            RescueCenter = "Humane Society of Pinellas",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 24,
                            Age = "6 years old",
                            Breed = "Mixed Breed",
                            CatOrDog = "dog",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(5050),
                            Description = "",
                            Gender = "Female",
                            GoodWith = "cat",
                            GoodWithSmallChildren = false,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1588088809/ginger_r2yi1s.jpg",
                            IsActive = false,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Ginger",
                            NeedYard = true,
                            RescueCenter = "Humane Society of Pinellas",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 25,
                            Age = "8 months old",
                            Breed = "Labardor Retriever",
                            CatOrDog = "dog",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(5070),
                            Description = "",
                            Gender = "Male",
                            GoodWith = "cat and dog",
                            GoodWithSmallChildren = false,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1588090091/wilson_nukavk.jpg",
                            IsActive = false,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Wilson",
                            NeedYard = true,
                            RescueCenter = "Humane Society of Pinellas",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 26,
                            Age = "9 years old",
                            Breed = "Pomeranian",
                            CatOrDog = "dog",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(5220),
                            Description = "",
                            Gender = "Female",
                            GoodWith = "none",
                            GoodWithSmallChildren = false,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1588090092/penny_bzlvft.jpg",
                            IsActive = false,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Penny",
                            NeedYard = true,
                            RescueCenter = "PetPal Animal Shelter",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 27,
                            Age = "6 months old",
                            Breed = "Domestic Long Hair",
                            CatOrDog = "cat",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(5240),
                            Description = "",
                            Gender = "Female",
                            GoodWith = "dog",
                            GoodWithSmallChildren = true,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1588090490/marley_vlsojk.jpg",
                            IsActive = false,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Marley",
                            NeedYard = true,
                            RescueCenter = "PetPal Animal Shelter",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 28,
                            Age = "2 years old",
                            Breed = "Tabby",
                            CatOrDog = "cat",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(5260),
                            Description = "",
                            Gender = "Female",
                            GoodWith = "cat",
                            GoodWithSmallChildren = true,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1588090489/amber_j0odow.jpg",
                            IsActive = false,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Amber",
                            NeedYard = true,
                            RescueCenter = "PetPal Animal Shelter",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 29,
                            Age = "4 years old",
                            Breed = "Domestic Medium hair",
                            CatOrDog = "cat",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(5280),
                            Description = "",
                            Gender = "Male",
                            GoodWith = "cat and dog",
                            GoodWithSmallChildren = true,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1588090489/oswald_j074v2.jpg",
                            IsActive = false,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Oswald",
                            NeedYard = true,
                            RescueCenter = "Humane Society of Pinellas",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 30,
                            Age = "1 years old",
                            Breed = "Domestic Long Hair",
                            CatOrDog = "cat",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(5300),
                            Description = "",
                            Gender = "Female",
                            GoodWith = "none",
                            GoodWithSmallChildren = true,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1588090488/whitney_fzymak.jpg",
                            IsActive = false,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Whitney",
                            NeedYard = true,
                            RescueCenter = "Humane Society of Pinellas",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 31,
                            Age = "1 years old",
                            Breed = "Grey Tabby",
                            CatOrDog = "cat",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(5320),
                            Description = "",
                            Gender = "Male",
                            GoodWith = "cat and dog",
                            GoodWithSmallChildren = true,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1588090486/ricky_skjqft.jpg",
                            IsActive = true,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Ricky",
                            NeedYard = false,
                            RescueCenter = "Humane Society of Pinellas",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 32,
                            Age = "2 years old",
                            Breed = "Sphinx",
                            CatOrDog = "cat",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(5340),
                            Description = "",
                            Gender = "Female",
                            GoodWith = "none",
                            GoodWithSmallChildren = true,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1588090485/sasha_zsz48a.jpg",
                            IsActive = true,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Sasha",
                            NeedYard = false,
                            RescueCenter = "PetPal Animal Shelter",
                            Zipcode = "33713"
                        },
                        new
                        {
                            Id = 33,
                            Age = "1 years old",
                            Breed = "Domestic Short Hair",
                            CatOrDog = "cat",
                            DateAdded = new DateTime(2020, 4, 28, 12, 21, 48, 725, DateTimeKind.Local).AddTicks(5370),
                            Description = "",
                            Gender = "Male",
                            GoodWith = "cat",
                            GoodWithSmallChildren = false,
                            HousingType = "house",
                            ImageUrl = "https://res.cloudinary.com/do8vvvqfj/image/upload/v1588090482/jenkins_eviv7m.jpg",
                            IsActive = false,
                            IsNeutered = true,
                            IsVaccinated = true,
                            Name = "Jenkins",
                            NeedYard = false,
                            RescueCenter = "PetPal Animal Shelter",
                            Zipcode = "33713"
                        });
                });

            modelBuilder.Entity("CapstoneProject.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("CapstoneProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Age")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("text");

                    b.Property<bool>("HaveYard")
                        .HasColumnType("boolean");

                    b.Property<string>("HousingType")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("LookingFor")
                        .HasColumnType("text");

                    b.Property<bool>("SmallChildren")
                        .HasColumnType("boolean");

                    b.Property<string>("TypeOfOtherAnimal")
                        .HasColumnType("text");

                    b.Property<string>("Zipcode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CapstoneProject.Models.Favorite", b =>
                {
                    b.HasOne("CapstoneProject.Models.Animal", "animal")
                        .WithMany("Favorites")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapstoneProject.Models.User", "user")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
